### ISSUE TITLE
MESSAGE_NO_DELETE rule is not working

### ISSUE THREAD

**Issue by lisette-rz** [bufbuild/buf-breaking-action#140] opened 2024-07-08 17:07 UTC
buf-breaking-action passes when I delete a message struct from the protobuf, causing a breaking change further.

Sample:
```
message Address {
  string city = 1;
  string state = 2;
  int32 zip = 3;
}
message Person {
  string name = 1;
  int32 age =2 ;
  Address address = 3;
}
```

If I remove the Address message struct, the breaking action still passes, which will provoke a compatibility error with the schema registry in Confluent.

```
message Person {
  string name = 1;
  int32 age = 2 ;
  reserved "address";
  reserved 3;
}
```

Expected result:
It should fail

**Comment by nicksnyder** [comment] 2024-07-08 18:19
The behavior you are expecting should work. If you are not seeing this behavior, then it is likely a configuration issue, but we would need more information to help you diagnose what the issue is. A complete, reproducible example would be ideal, but at the very least we would need to know your buf.yaml, and how you have configured this action in your workflow.

**Comment by lisette-rz** [comment] 2024-07-08 18:25
This is the configuration I'm using in `buf.yaml`:
```
version: v1
breaking:
  use:
    - FILE
  except:
    - FILE_NO_DELETE
    - FIELD_NO_DELETE
```

The buf version is: 1.34.0 but I also tried downgrading to 1.22.0 without success.
The other rules are working fine.

**Comment by nicksnyder** [comment] 2024-07-08 20:14
I reproduced your setup and the action correctly failed with the error `Previously present message "Address" was deleted from file.`

Example:
https://github.com/nicksnyder/testbuf/pull/1/files

Going to close this since I am unable to reproduce the error you are reporting given the info you provided. Feel free to re-open if you have a reproducible example that demonstrates incorrect behavior.

**Closed by nicksnyder** 2024-07-08 20:14 UTC
