### ISSUE TITLE
Unprocessible Entity

### ISSUE THREAD

**Issue by jzelinskie** [bufbuild/buf-breaking-action#4] opened 2021-07-12 18:44 UTC
Our action might be misconfigured, but it's failing to run with this error and this config:

>Failed to write comments in-line: Unprocessable Entity: "Pull request review thread path is invalid and Pull request review thread diff hunk can't be blank"

```yaml
    ...
    - uses: bufbuild/buf-breaking-action@v0.2.0
      if: github.event_name == 'pull_request'
      env:
        BUF_INPUT_HTTPS_USERNAME: "${{ github.actor }}"
        BUF_INPUT_HTTPS_PASSWORD: "${{ github.token }}"
      with:
        input: "./dirthatcontainsbufyaml"
        against: "https://github.com/organization/repository.git#branch=master"
        github_token: "${{ github.token }}"
        buf_token: "${{ secrets.BUF_TOKEN }}"
```

**Comment by amckinney** [comment] 2021-07-12 18:58
At first glance, it looks like you're targeting a nested directory input (`./dirthatcontainsbufyaml`), but aren't including that in your `--against` reference. You can use the `subdir` parameter for that, so you would have the following (this is explained in greater detail in the [README.md](https://github.com/bufbuild/buf-breaking-action#inputs)):

```yaml
    ...
    - uses: bufbuild/buf-breaking-action@v0.2.0
      if: github.event_name == 'pull_request'
      env:
        BUF_INPUT_HTTPS_USERNAME: "${{ github.actor }}"
        BUF_INPUT_HTTPS_PASSWORD: "${{ github.token }}"
      with:
        input: "dirthatcontainsbufyaml"
        against: "https://github.com/organization/repository.git#branch=master,subdir=dirthatcontainsbufyaml"
        github_token: "${{ github.token }}"
        buf_token: "${{ secrets.BUF_TOKEN }}"
```

Regardless, the error message clearly isn't very helpful - I'll see what we can do to clean that up. Let me know if this works for you! Otherwise, I'll keep investigating and try to reproduce your error to see what's going wrong.

**Comment by jzelinskie** [comment] 2021-07-12 20:16
Totally missed that -- adding the subdir fixed it. Thanks for the quick response.

**Comment by amckinney** [comment] 2021-07-12 21:15
No problem! I'll close this issue, but I will come back around to fixing up these error messages (tracking an issue internally).

**Closed by amckinney** 2021-07-12 21:15 UTC
